# https://golangci-lint.run/usage/configuration/

linters-settings:
  goimports:
    local-prefixes: github.com/armsnyder/a2s-exporter

linters:
  enable:
    - gocritic
    - gofmt
    - goimports
    - misspell
    - revive
    - testpackage
    - unconvert
    - whitespace
