# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20", "1.21", "1.22"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -cover ./...

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1

  release-please:
    runs-on: ubuntu-latest
    needs: [Test, Lint]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.PAT }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

  Docker:
    runs-on: ubuntu-latest
    needs:
      - Test
      - Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: armsnyder/a2s-exporter

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          username: armsnyder
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build
        if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: BUILD_VERSION=${{ steps.meta.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker build and push
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: BUILD_VERSION=${{ steps.meta.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sync Docker readme
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: meeDamian/sync-readme@v1.0.6
        with:
          pass: ${{ secrets.DOCKERHUB_PASSWORD }}
          description: true
